apiVersion: apps/v1
kind: Deployment
metadata:
  name: solarwind-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solarwind-nginx
  template:
    metadata:
      labels:
        app: solarwind-nginx
    spec:
      containers:
      - name: solarwind-nginx
        image: vhalme/solarwind-nginx:x86_0.0.16
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: NGINX_HOME
          value: "/nginx"
        - name: SSL_CERTS_CONF
          value: "ssl/zero-ssl/ssl-certs.conf"
        - name: WEB_HTTP_PORT
          value: "3003"
        - name: API_HTTP_PORT
          value: "3002"
        - name: AUTH_HTTP_PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: solarwind-nginx
spec:
  selector:
    app: solarwind-nginx
  ports:
  - name: solarwind-nginx
    protocol: TCP
    port: 80
    targetPort: 80
  - name: solarwind-nginx-ssl
    protocol: TCP
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: solarwind-nginx-lb
spec:
  selector:
    app: solarwind-nginx
  ports:
  - name: solarwind-nginx
    protocol: TCP
    port: 80
    targetPort: 80
  - name: solarwind-nginx-ssl
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
